package com.example.myvillage.client.cultivation.panel;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * The meridian diagram on the meditation page as data: acupoints and channels in the normalised
 * square of the seated-figure texture ({@code textures/gui/cultivation/meridian_figure.png},
 * generated by {@code tools/gen_meridian_figure.py}; 0,0 is the top-left, 1,1 the bottom-right).
 * The figure sits in profile facing right, so the governing vessel rises along the back and the
 * conception vessel descends along the front; together they make the small circuit through the
 * lower dantian.
 *
 * <p>This class only describes the drawing. It holds no player state and derives no gameplay
 * value; how brightly a channel is drawn is decided per frame by {@link MeridianLook}. A later
 * meridian system can light channels individually by their {@link Channel#id()}.
 */
public final class MeridianChart {
    /** The vessel a channel belongs to. */
    public enum Vessel {
        /** 督脉: up the spine from the perineum to the crown. */
        GOVERNING,
        /** 任脉: down the front from the crown to the perineum. */
        CONCEPTION,
        /** A hand channel: from the chest down the arm to the palm. */
        HAND,
        /** A foot channel: from the perineum along the leg to the sole. */
        FOOT
    }

    /** How prominently an acupoint is drawn. */
    public enum Tier {
        /** The lower dantian; the panel draws it as a gauge. */
        DANTIAN,
        /** A named point drawn with its label. */
        MAJOR,
        /** A point drawn as a small node without a label. */
        MINOR
    }

    /** Which way a label extends from its anchor. */
    public enum LabelSide {
        /** Text ends at the anchor. */
        LEFT,
        /** Text starts at the anchor. */
        RIGHT
    }

    /** Where a point's name is written, in the same normalised square as the point. */
    public record Label(LabelSide side, float x, float y) {
    }

    public record Acupoint(String id, String translationKey, float x, float y, Tier tier, Optional<Label> label) {
    }

    /** One stop of a channel's route: an acupoint, or a shaping waypoint between acupoints. */
    public record Stop(Optional<String> acupoint, float x, float y) {
    }

    /** A channel's route in its stored direction, from {@code stops.get(0)} to the last stop. */
    public record Channel(String id, Vessel vessel, List<Stop> stops) {
        public String from() {
            return stops.get(0).acupoint().orElseThrow();
        }

        public String to() {
            return stops.get(stops.size() - 1).acupoint().orElseThrow();
        }
    }

    public static final String DANTIAN = "dantian";
    public static final String HUIYIN = "huiyin";
    public static final String BAIHUI = "baihui";
    /** 玉枕, the third pass of the small circuit, where a bottleneck is drawn. */
    public static final String YUZHEN = "yuzhen";

    private static final List<Acupoint> POINTS = List.of(
            point("huiyin", "screen.myvillage.cultivation.acupoint.huiyin", 0.478F, 0.752F, Tier.MAJOR,
                    label(LabelSide.LEFT, 0.300F, 0.770F)),
            point("weilu", "screen.myvillage.cultivation.acupoint.weilu", 0.404F, 0.700F, Tier.MINOR, null),
            point("mingmen", "screen.myvillage.cultivation.acupoint.mingmen", 0.452F, 0.530F, Tier.MAJOR,
                    label(LabelSide.LEFT, 0.300F, 0.530F)),
            point("jiaji", "screen.myvillage.cultivation.acupoint.jiaji", 0.430F, 0.400F, Tier.MINOR, null),
            point("dazhui", "screen.myvillage.cultivation.acupoint.dazhui", 0.452F, 0.272F, Tier.MAJOR,
                    label(LabelSide.LEFT, 0.300F, 0.290F)),
            point("yuzhen", "screen.myvillage.cultivation.acupoint.yuzhen", 0.455F, 0.168F, Tier.MINOR, null),
            point("baihui", "screen.myvillage.cultivation.acupoint.baihui", 0.512F, 0.080F, Tier.MAJOR,
                    label(LabelSide.RIGHT, 0.660F, 0.088F)),
            point("yintang", "screen.myvillage.cultivation.acupoint.yintang", 0.556F, 0.118F, Tier.MINOR, null),
            point("chengjiang", "screen.myvillage.cultivation.acupoint.chengjiang", 0.550F, 0.200F, Tier.MINOR, null),
            point("danzhong", "screen.myvillage.cultivation.acupoint.danzhong", 0.594F, 0.385F, Tier.MAJOR,
                    label(LabelSide.RIGHT, 0.700F, 0.375F)),
            point("dantian", "screen.myvillage.cultivation.acupoint.dantian", 0.552F, 0.608F, Tier.DANTIAN,
                    label(LabelSide.RIGHT, 0.700F, 0.505F)),
            point("laogong", "screen.myvillage.cultivation.acupoint.laogong", 0.802F, 0.664F, Tier.MINOR, null),
            point("yongquan", "screen.myvillage.cultivation.acupoint.yongquan", 0.668F, 0.654F, Tier.MINOR, null));

    private static final List<Channel> CHANNELS = List.of(
            channel("du", Vessel.GOVERNING, route(
                    "huiyin", via(0.430F, 0.736F), "weilu", via(0.420F, 0.620F), "mingmen",
                    "jiaji", via(0.430F, 0.330F), "dazhui", via(0.455F, 0.222F), "yuzhen",
                    via(0.470F, 0.100F), "baihui")),
            channel("ren", Vessel.CONCEPTION, route(
                    "baihui", via(0.548F, 0.092F), "yintang", via(0.566F, 0.160F), "chengjiang",
                    via(0.560F, 0.262F), "danzhong", via(0.598F, 0.480F), "dantian",
                    via(0.530F, 0.700F), "huiyin")),
            channel("hand", Vessel.HAND, route(
                    "danzhong", via(0.536F, 0.330F), via(0.502F, 0.430F), via(0.504F, 0.548F),
                    via(0.640F, 0.603F), via(0.750F, 0.658F), "laogong")),
            channel("foot", Vessel.FOOT, route(
                    "huiyin", via(0.620F, 0.770F), via(0.800F, 0.780F), via(0.904F, 0.752F),
                    via(0.840F, 0.700F), via(0.740F, 0.694F), "yongquan")));

    /** The small circuit in flow order: up the governing vessel, then down the conception vessel. */
    private static final List<String> SMALL_CIRCUIT = List.of("du", "ren");

    private static final Map<String, Acupoint> BY_ID = index();

    private MeridianChart() {
    }

    public static List<Acupoint> points() {
        return POINTS;
    }

    public static List<Channel> channels() {
        return CHANNELS;
    }

    public static List<String> smallCircuit() {
        return SMALL_CIRCUIT;
    }

    public static Optional<Acupoint> point(String id) {
        return Optional.ofNullable(BY_ID.get(id));
    }

    public static Optional<Channel> channel(String id) {
        return CHANNELS.stream().filter(channel -> channel.id().equals(id)).findFirst();
    }

    private static Map<String, Acupoint> index() {
        Map<String, Acupoint> byId = new LinkedHashMap<>();
        for (Acupoint point : POINTS) {
            if (byId.put(point.id(), point) != null) {
                throw new IllegalStateException("Duplicate acupoint " + point.id());
            }
        }
        return Map.copyOf(byId);
    }

    private static Acupoint point(String id, String key, float x, float y, Tier tier, Label label) {
        return new Acupoint(id, key, x, y, tier, Optional.ofNullable(label));
    }

    private static Label label(LabelSide side, float x, float y) {
        return new Label(side, x, y);
    }

    private static Stop via(float x, float y) {
        return new Stop(Optional.empty(), x, y);
    }

    /** Resolves acupoint ids to their positions; other arguments are {@link #via} waypoints. */
    private static List<Stop> route(Object... stops) {
        List<Stop> resolved = new ArrayList<>(stops.length);
        for (Object stop : stops) {
            if (stop instanceof Stop waypoint) {
                resolved.add(waypoint);
            } else {
                String id = (String) stop;
                Acupoint point = POINTS.stream()
                        .filter(candidate -> candidate.id().equals(id))
                        .findFirst()
                        .orElseThrow(() -> new IllegalStateException("Unknown acupoint " + id));
                resolved.add(new Stop(Optional.of(id), point.x(), point.y()));
            }
        }
        return List.copyOf(resolved);
    }

    private static Channel channel(String id, Vessel vessel, List<Stop> stops) {
        return new Channel(id, vessel, stops);
    }
}
