"""Regression guards for the non-mansion compound families.

Run from the repository root:
    python3 tools/buildgen/tests/test_chinese_courtyard_regression.py

Byte-stability invariant (path-surface-zoning task 4.5):
  - ``cultivation_sect_*`` and every ``medieval_*`` archetype NBT stay
    byte-stable across a regeneration. The surface-zoning change re-materials
    the ground + path overlay for the courtyard/mansion families that carry the
    new ``PATH_FORMAL`` / ``GROUND_YARD_HEART`` / ``PATH_GALLERY`` / ``PATH_ALLEY``
    slots; the sect/medieval styles do not adopt those slots and do not run the
    surface-zoned passes, so they MUST regenerate byte-for-byte unchanged.

  - ``chinese_courtyard_*`` is intentionally NOT in the byte-stable set: its
    gallery cells now resolve to ``PATH_GALLERY`` (oak_planks) instead of the
    old ``GROUND_YARD_UNDER_EAVE`` (stone_bricks), and its formal backbone now
    resolves to ``PATH_FORMAL`` (smooth_stone) instead of ``GROUND_PATH``
    (gravel). ``chinese_mansion_*`` is likewise regenerated by the surface-zoning
    change.

``chinese_mansion_*`` orientation byte-stability is covered separately by
``test_mansion_orientation_regression.py``.
"""

from __future__ import annotations

import hashlib
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
STRUCTURES = ROOT / "src/main/resources/data/myvillage/structure"
MEDIEVAL_ARCHETYPES = (
    "small_house", "medium_house", "blacksmith", "small_shop",
    "medium_shop", "big_house",
)


def _legacy_files() -> list[Path]:
    """Byte-stable set for the surface-zoning change: sect + medieval only.

    The courtyard, town, and mansion families are regenerated by this change
    (their styles adopt the surface-zoning slots); the sect + medieval families
    do not adopt the slots and do not run the surface-zoned passes, so they
    must stay byte-for-byte identical.
    """
    files = list(STRUCTURES.glob("cultivation_sect_*.nbt"))
    for archetype in MEDIEVAL_ARCHETYPES:
        files.extend(STRUCTURES.glob(f"{archetype}_*.nbt"))
    return sorted(files)


def _hashes() -> dict[str, str]:
    return {str(path.relative_to(ROOT)): hashlib.sha256(path.read_bytes()).hexdigest()
            for path in _legacy_files()}


def _run(cmd: list[str]) -> None:
    """Run a generation subprocess, robust to a Windows file-write flake.

    On some Windows setups, redirecting the child's stdout to DEVNULL makes the
    child's ``open(path, "wb")`` raise ``OSError [Errno 22]`` (an interaction
    with a shell/AV stdout hook), so we capture stdout to a PIPE instead and
    retry once on a transient failure.
    """
    for attempt in range(2):
        proc = subprocess.run(cmd, cwd=ROOT, stdout=subprocess.PIPE,
                              stderr=subprocess.STDOUT, text=True)
        if proc.returncode == 0:
            return
        if attempt == 0 and "Errno 22" in (proc.stdout or ""):
            continue
        raise AssertionError(
            f"command failed ({proc.returncode}): {' '.join(cmd)}\n{proc.stdout}")


def main() -> int:
    before = _hashes()
    if not before:
        raise AssertionError(
            "legacy sect / medieval structure libraries are missing")
    # Default group is chinese_courtyard at base-seed 20260614 (the canonical
    # committed seed); its full-profile run also regenerates the standalone
    # medieval archetypes (small_house / medium_house / blacksmith / small_shop /
    # medium_shop / big_house). The surface-zoning change adopts the new slots
    # only on chinese_courtyard/chinese_mansion, so the medieval archetypes —
    # whose style (medieval_village.json) does not carry the new slots — MUST
    # come back byte-for-byte unchanged.
    _run([sys.executable, "tools/generate_compound_library.py", "--profile", "full"])
    # Sect ships exactly 2 NBTs at base-seed 20260616; regenerate at the same
    # count + seed so the byte-stable glob (cultivation_sect_*.nbt) compares
    # like-for-like against the committed tree. The sect style does not adopt
    # the surface-zoning slots, so it MUST come back unchanged.
    _run([sys.executable, "tools/generate_compound_library.py",
          "--group", "cultivation_sect", "--count", "2",
          "--base-seed", "20260616", "--profile", "full"])
    after = _hashes()
    if before != after:
        changed = sorted(set(before) | set(after), key=str)
        changed = [name for name in changed if before.get(name) != after.get(name)]
        raise AssertionError(
            f"surface-zoning change altered byte-stable sect/medieval NBTs: {changed}")
    print(f"OK byte stability: {len(before)} sect/medieval NBTs unchanged")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
