"""Regression guards for the isolated Chinese-courtyard rebuild.

Run from the repository root:
    python3 tools/buildgen/tests/test_chinese_courtyard_regression.py

Two invariants (fix-courtyard-ground-walkability task 3.4):
  - ``cultivation_sect_*`` and every ``medieval_*`` archetype NBT stay
    byte-stable across a regeneration (this change touches only
    ``generate_compound`` + ``generate_small_courtyard`` + the two style JSONs,
    so sect / medieval output must be untouched).
  - ``cultivation_town_*`` NBTs are *expected* to change (their embedded
    small-courtyards get the new ground + path layers). They are excluded from
    the byte-stable set; their walkability is checked by validate_compound /
    validate_small_courtyard instead.
"""

from __future__ import annotations

import hashlib
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
STRUCTURES = ROOT / "src/main/resources/data/myvillage/structure"
MEDIEVAL_ARCHETYPES = (
    "small_house", "medium_house", "blacksmith", "small_shop",
    "medium_shop", "big_house",
)


def _legacy_files() -> list[Path]:
    """Byte-stable set: sect compounds + medieval archetypes.

    ``cultivation_town_*`` is intentionally excluded — its embedded
    small-courtyards are regenerated by fix-courtyard-ground-walkability.
    """
    files = list(STRUCTURES.glob("cultivation_sect_*.nbt"))
    for archetype in MEDIEVAL_ARCHETYPES:
        files.extend(STRUCTURES.glob(f"{archetype}_*.nbt"))
    return sorted(files)


def _hashes() -> dict[str, str]:
    return {str(path.relative_to(ROOT)): hashlib.sha256(path.read_bytes()).hexdigest()
            for path in _legacy_files()}


def _run(cmd: list[str]) -> None:
    """Run a generation subprocess, robust to a Windows file-write flake.

    On some Windows setups, redirecting the child's stdout to DEVNULL makes the
    child's ``open(path, "wb")`` raise ``OSError [Errno 22]`` (an interaction
    with a shell/AV stdout hook), so we capture stdout to a PIPE instead and
    retry once on a transient failure.
    """
    for attempt in range(2):
        proc = subprocess.run(cmd, cwd=ROOT, stdout=subprocess.PIPE,
                              stderr=subprocess.STDOUT, text=True)
        if proc.returncode == 0:
            return
        if attempt == 0 and "Errno 22" in (proc.stdout or ""):
            continue
        raise AssertionError(
            f"command failed ({proc.returncode}): {' '.join(cmd)}\n{proc.stdout}")


def main() -> int:
    before = _hashes()
    if not before:
        raise AssertionError("legacy cultivation_sect / medieval structure libraries are missing")
    _run([sys.executable, "tools/generate_compound_library.py", "--profile", "full"])
    # cultivation_town NBTs are expected to change (their embedded
    # small-courtyards get the new ground + path layers); regenerate them with
    # the canonical base-seed so the non-byte-stable set is well-defined.
    _run([sys.executable, "tools/generate_compound_library.py",
          "--group", "cultivation_town", "--count", "6",
          "--base-seed", "20260617", "--profile", "full"])
    # Sect ships exactly 2 NBTs at base-seed 20260616; regenerate at the same
    # count + seed so the byte-stable glob (cultivation_sect_*.nbt) compares
    # like-for-like against the committed tree.
    _run([sys.executable, "tools/generate_compound_library.py",
          "--group", "cultivation_sect", "--count", "2",
          "--base-seed", "20260616", "--profile", "full"])
    after = _hashes()
    if before != after:
        changed = sorted(set(before) | set(after), key=str)
        changed = [name for name in changed if before.get(name) != after.get(name)]
        raise AssertionError(
            f"Chinese courtyard generation changed byte-stable NBTs: {changed}")
    print(f"OK legacy byte stability: {len(before)} cultivation_sect/medieval NBTs unchanged")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
