"""Regression guards for the non-mansion compound families.

Run from the repository root:
    python3 tools/buildgen/tests/test_chinese_courtyard_regression.py

Byte-stability invariant (rebuild-mansion-enclosure-plan task 6.1):
  - ``chinese_courtyard_*``, ``cultivation_town_*``, ``cultivation_sect_*`` and
    every ``medieval_*`` archetype NBT stay byte-stable across a regeneration.
    The mansion enclosure-plan rewrite touches only the ``chinese_mansion``
    path (``generate_mansion`` + ``validate_mansion`` + the enclosure planner),
    so every other family MUST regenerate byte-for-byte unchanged — they must
    not be regenerated by this change.

``chinese_mansion_*`` is intentionally NOT in the byte-stable set: those NBTs
are regenerated by this change (task 7.1). The orientation default-south
byte-stability is covered separately by
``test_mansion_orientation_regression.py``.
"""

from __future__ import annotations

import hashlib
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
STRUCTURES = ROOT / "src/main/resources/data/myvillage/structure"
MEDIEVAL_ARCHETYPES = (
    "small_house", "medium_house", "blacksmith", "small_shop",
    "medium_shop", "big_house",
)


def _legacy_files() -> list[Path]:
    """Byte-stable set for the mansion change: every non-mansion family.

    ``chinese_mansion_*`` is excluded (regenerated by this change); everything
    else — courtyard, town, sect, and the medieval archetypes — must stay
    byte-for-byte identical.
    """
    files = list(STRUCTURES.glob("chinese_courtyard_*.nbt"))
    files.extend(STRUCTURES.glob("cultivation_town_*.nbt"))
    files.extend(STRUCTURES.glob("cultivation_sect_*.nbt"))
    for archetype in MEDIEVAL_ARCHETYPES:
        files.extend(STRUCTURES.glob(f"{archetype}_*.nbt"))
    return sorted(files)


def _hashes() -> dict[str, str]:
    return {str(path.relative_to(ROOT)): hashlib.sha256(path.read_bytes()).hexdigest()
            for path in _legacy_files()}


def _run(cmd: list[str]) -> None:
    """Run a generation subprocess, robust to a Windows file-write flake.

    On some Windows setups, redirecting the child's stdout to DEVNULL makes the
    child's ``open(path, "wb")`` raise ``OSError [Errno 22]`` (an interaction
    with a shell/AV stdout hook), so we capture stdout to a PIPE instead and
    retry once on a transient failure.
    """
    for attempt in range(2):
        proc = subprocess.run(cmd, cwd=ROOT, stdout=subprocess.PIPE,
                              stderr=subprocess.STDOUT, text=True)
        if proc.returncode == 0:
            return
        if attempt == 0 and "Errno 22" in (proc.stdout or ""):
            continue
        raise AssertionError(
            f"command failed ({proc.returncode}): {' '.join(cmd)}\n{proc.stdout}")


def main() -> int:
    before = _hashes()
    if not before:
        raise AssertionError(
            "legacy courtyard / town / sect / medieval structure libraries are missing")
    # Default group is chinese_courtyard at base-seed 20260614 (the canonical
    # committed seed), so the full-profile run regenerates the courtyard family.
    _run([sys.executable, "tools/generate_compound_library.py", "--profile", "full"])
    # Regenerate town + sect at their canonical base-seeds so the byte-stable
    # globs compare like-for-like against the committed tree. The mansion change
    # does not touch these paths, so all three families must come back unchanged.
    _run([sys.executable, "tools/generate_compound_library.py",
          "--group", "cultivation_town", "--count", "6",
          "--base-seed", "20260617", "--profile", "full"])
    # Sect ships exactly 2 NBTs at base-seed 20260616; regenerate at the same
    # count + seed so the byte-stable glob (cultivation_sect_*.nbt) compares
    # like-for-like against the committed tree.
    _run([sys.executable, "tools/generate_compound_library.py",
          "--group", "cultivation_sect", "--count", "2",
          "--base-seed", "20260616", "--profile", "full"])
    after = _hashes()
    if before != after:
        changed = sorted(set(before) | set(after), key=str)
        changed = [name for name in changed if before.get(name) != after.get(name)]
        raise AssertionError(
            f"mansion change altered byte-stable non-mansion NBTs: {changed}")
    print(f"OK byte stability: {len(before)} courtyard/town/sect/medieval NBTs unchanged")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
