#!/usr/bin/env python3
"""Copy a generated .nbt structure into a Minecraft test world's generated structures folder."""

from __future__ import annotations

import argparse
import os
import platform
import re
import shutil
import sys
from pathlib import Path

_RESOURCE_ID_RE = re.compile(r"^[a-z0-9_.-]+$")


def default_saves_dir() -> Path:
    system = platform.system().lower()
    home = Path.home()
    if system == "windows":
        appdata = os.environ.get("APPDATA")
        if appdata:
            return Path(appdata) / ".minecraft" / "saves"
        return home / "AppData" / "Roaming" / ".minecraft" / "saves"
    if system == "darwin":
        return home / "Library" / "Application Support" / "minecraft" / "saves"
    return home / ".minecraft" / "saves"


def fail(message: str) -> int:
    print(f"EXPORT FAILED: {message}", file=sys.stderr)
    return 1


def main() -> int:
    parser = argparse.ArgumentParser(description="Export a Minecraft structure .nbt to a test world's generated namespace")
    parser.add_argument("input_nbt", help="Input .nbt file generated by json_to_nbt.py")
    parser.add_argument("--world", required=True, help="Minecraft save/world folder name, e.g. StructureTest")
    parser.add_argument("--namespace", required=True, help="Resource namespace, e.g. myvillage")
    parser.add_argument("--name", required=True, help="Structure resource name without .nbt, e.g. test_house_02")
    parser.add_argument("--saves-dir", default=None, help="Override Minecraft saves root directory")
    args = parser.parse_args()

    source = Path(args.input_nbt).expanduser().resolve()
    if not source.is_file():
        return fail(f"input .nbt does not exist: {source}")
    if source.suffix.lower() != ".nbt":
        return fail(f"input file should end with .nbt: {source}")

    namespace = args.namespace.strip()
    name = args.name.strip()
    if not _RESOURCE_ID_RE.match(namespace):
        return fail(f"invalid namespace {namespace!r}; use lowercase letters, digits, underscore, hyphen, or dot")
    if not _RESOURCE_ID_RE.match(name):
        return fail(f"invalid structure name {name!r}; use lowercase letters, digits, underscore, hyphen, or dot")

    saves_root = Path(args.saves_dir).expanduser().resolve() if args.saves_dir else default_saves_dir()
    if not saves_root.is_dir():
        return fail(
            "Minecraft saves directory was not found: "
            f"{saves_root}\nUse --saves-dir to specify the saves root, for example:\n"
            "  python tools/export_to_world.py out/test_house_02_1_21_1.nbt --world StructureTest --namespace myvillage --name test_house_02 --saves-dir <path-to-saves>"
        )

    world_dir = saves_root / args.world
    if not world_dir.is_dir():
        return fail(
            f"world folder was not found: {world_dir}\n"
            "Create/open the test world in Minecraft first, or pass the correct --world name."
        )

    dest_dir = world_dir / "generated" / namespace / "structures"
    dest_dir.mkdir(parents=True, exist_ok=True)
    dest = dest_dir / f"{name}.nbt"
    shutil.copy2(source, dest)

    print(f"copied: {source}")
    print(f"to:     {dest}")
    print("game test command:")
    print(f"/place template {namespace}:{name} ~ ~ ~")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
