#!/usr/bin/env python3
"""Validate MyVillage item/block-item registration and client resources."""

from __future__ import annotations

import json
import re
import struct
import sys
import zlib
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
ASSET_ROOT = ROOT / "src" / "main" / "resources" / "assets" / "myvillage"
MOD_ITEMS = ROOT / "src" / "main" / "java" / "com" / "example" / "myvillage" / "item" / "ModItems.java"
MOD_BLOCKS = ROOT / "src" / "main" / "java" / "com" / "example" / "myvillage" / "block" / "ModBlocks.java"
ROCKERY_BLOCK = ROOT / "src" / "main" / "java" / "com" / "example" / "myvillage" / "block" / "RockeryBlock.java"
COMBAT_WEAPON_ITEM = ROOT / "src" / "main" / "java" / "com" / "example" / "myvillage" / "item" / "CombatWeaponItem.java"
COMBAT_WEAPON_DATA = ROOT / "src" / "main" / "resources" / "data" / "myvillage" / "combat" / "weapon"
LANG = ASSET_ROOT / "lang" / "en_us.json"
ZH_LANG = ASSET_ROOT / "lang" / "zh_cn.json"

# An item with a combat weapon entry (data/myvillage/combat/weapon/*.json) must be registered as a
# CombatWeaponItem: a landed combat hit costs durability, and on a plain SwordItem that data-only change
# replays the vanilla equip animation, which drops the first-person weapon after every hit.
COMBAT_WEAPON_CLASS = "CombatWeaponItem"
# The re-equip rule CombatWeaponItem must keep: vanilla's behaviour minus the durability replay
# (same item, count and components with minecraft:damage ignored: no re-equip; slotChanged unused).
# Pinned: the override exists and the rule refers to the damage component; the method body is free.
COMBAT_WEAPON_RULE = ("boolean shouldCauseReequipAnimation(", "DataComponents.DAMAGE")
COMBAT_WEAPON_RULE_FORBIDDEN = ("slotChanged ||", "|| slotChanged")

# SwordItem.createAttributes(Tiers.DIAMOND, <attack bonus>, <attack speed>) per item.
SWORD_ATTRIBUTES = (3, "-2.4F")
SPEAR_ATTRIBUTES = (4, "-2.8F")

# Diamond-tier SwordItem registrations (the Lingxiao spear is a SwordItem with spear attributes):
# (item id, holder, en_us name, zh_cn name, error key, binary-alpha icon, attributes).
SWORD_CONTRACTS = (
    (
        "qingfeng_sword",
        "QINGFENG_SWORD",
        "Qingfeng Sword",
        "青锋剑",
        "qingfeng",
        False,
        SWORD_ATTRIBUTES,
    ),
    (
        "xuanyue_zhenshan_sword",
        "XUANYUE_ZHENSHAN_SWORD",
        "Xuanyue Zhenshan Sword",
        "玄岳镇山剑",
        "xuanyue_zhenshan",
        True,
        SWORD_ATTRIBUTES,
    ),
    (
        "chilian_lihuo_sword",
        "CHILIAN_LIHUO_SWORD",
        "Chilian Lihuo Sword",
        "赤炼离火剑",
        "chilian_lihuo",
        True,
        SWORD_ATTRIBUTES,
    ),
    (
        "qingxiao_liuyun_sword",
        "QINGXIAO_LIUYUN_SWORD",
        "Qingxiao Liuyun Sword",
        "青霄流云剑",
        "qingxiao_liuyun",
        True,
        SWORD_ATTRIBUTES,
    ),
    (
        "lingxiao_spear",
        "LINGXIAO_SPEAR",
        "Lingxiao Spear",
        "凌霄枪",
        "lingxiao_spear",
        False,
        SPEAR_ATTRIBUTES,
    ),
)
CREATIVE_SWORD_ORDER = (
    "RIDEABLE_FLYING_SWORD",
    "QINGFENG_SWORD",
    "XUANYUE_ZHENSHAN_SWORD",
    "CHILIAN_LIHUO_SWORD",
    "QINGXIAO_LIUYUN_SWORD",
    "LINGXIAO_SPEAR",
    "LOW_GRADE_SPIRIT_STONE",
)


SEPARATE_TRANSFORMS_LOADER = "neoforge:separate_transforms"
DISPLAY_CONTEXTS = {"none", "thirdperson_lefthand", "thirdperson_righthand", "firstperson_lefthand",
                    "firstperson_righthand", "head", "gui", "ground", "fixed"}
GENERATED_PARENTS = {"minecraft:item/generated", "item/generated", "minecraft:item/handheld", "item/handheld"}
# Swords rendered as a 3D element model in hand (generated by tools/gen_qingfeng_sword_model.py).
# The Lingxiao spear's model comes from tools/gen_lingxiao_spear_model.py.
SWORD_3D_MODELS = {
    "qingfeng_sword": "myvillage:item/qingfeng_sword_3d",
    "lingxiao_spear": "myvillage:item/lingxiao_spear_3d",
}


def load_json(path: Path) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ValueError(f"{path}: invalid JSON: {exc}") from exc


def png_size(path: Path) -> tuple[int, int]:
    data = path.read_bytes()
    if not data.startswith(b"\x89PNG\r\n\x1a\n") or data[12:16] != b"IHDR":
        raise ValueError(f"{path}: not a PNG file")
    width, height = struct.unpack(">II", data[16:24])
    return width, height


def png_has_alpha(path: Path) -> bool:
    data = path.read_bytes()
    return (data.startswith(b"\x89PNG\r\n\x1a\n")
            and data[12:16] == b"IHDR"
            and data[25] in (4, 6))


def _paeth(a: int, b: int, c: int) -> int:
    estimate = a + b - c
    distance_a = abs(estimate - a)
    distance_b = abs(estimate - b)
    distance_c = abs(estimate - c)
    if distance_a <= distance_b and distance_a <= distance_c:
        return a
    return b if distance_b <= distance_c else c


def png_non_binary_alpha_count(path: Path) -> int:
    """Return the count of semi-transparent pixels in an 8-bit alpha PNG."""
    data = path.read_bytes()
    if not data.startswith(b"\x89PNG\r\n\x1a\n"):
        raise ValueError(f"{path}: not a PNG file")

    offset = 8
    width = height = channels = None
    idat = bytearray()
    while offset < len(data):
        if offset + 12 > len(data):
            raise ValueError(f"{path}: truncated PNG chunk")
        length = struct.unpack(">I", data[offset:offset + 4])[0]
        chunk_type = data[offset + 4:offset + 8]
        payload_end = offset + 8 + length
        if payload_end + 4 > len(data):
            raise ValueError(f"{path}: truncated PNG chunk")
        payload = data[offset + 8:payload_end]
        offset = payload_end + 4

        if chunk_type == b"IHDR":
            if len(payload) != 13:
                raise ValueError(f"{path}: invalid IHDR")
            width, height, bit_depth, color_type, compression, filtering, interlace = (
                struct.unpack(">IIBBBBB", payload)
            )
            channels = {4: 2, 6: 4}.get(color_type)
            if (bit_depth != 8 or channels is None or compression != 0
                    or filtering != 0 or interlace != 0):
                raise ValueError(
                    f"{path}: expected non-interlaced 8-bit grayscale-alpha or RGBA PNG")
        elif chunk_type == b"IDAT":
            idat.extend(payload)
        elif chunk_type == b"IEND":
            break

    if width is None or height is None or channels is None or not idat:
        raise ValueError(f"{path}: incomplete alpha PNG")

    raw = zlib.decompress(bytes(idat))
    stride = width * channels
    expected_length = height * (stride + 1)
    if len(raw) != expected_length:
        raise ValueError(
            f"{path}: unexpected decompressed byte count {len(raw)} != {expected_length}")

    previous = bytearray(stride)
    cursor = 0
    non_binary_alpha = 0
    for _ in range(height):
        filter_type = raw[cursor]
        cursor += 1
        scanline = bytearray(raw[cursor:cursor + stride])
        cursor += stride
        for index, value in enumerate(scanline):
            left = scanline[index - channels] if index >= channels else 0
            up = previous[index]
            up_left = previous[index - channels] if index >= channels else 0
            if filter_type == 1:
                scanline[index] = (value + left) & 0xFF
            elif filter_type == 2:
                scanline[index] = (value + up) & 0xFF
            elif filter_type == 3:
                scanline[index] = (value + ((left + up) // 2)) & 0xFF
            elif filter_type == 4:
                scanline[index] = (value + _paeth(left, up, up_left)) & 0xFF
            elif filter_type != 0:
                raise ValueError(f"{path}: unsupported PNG filter {filter_type}")

        non_binary_alpha += sum(
            alpha not in (0, 255)
            for alpha in scanline[channels - 1::channels]
        )
        previous = scanline

    return non_binary_alpha


def registered_items() -> set[str]:
    text = MOD_ITEMS.read_text(encoding="utf-8")
    explicit = re.findall(r'ITEMS\.registerItem\(\s*"([a-z0-9_./-]+)"', text, re.MULTILINE)
    simple = re.findall(r'ITEMS\.registerSimpleItem\(\s*"([a-z0-9_./-]+)"', text, re.MULTILINE)
    return set(explicit) | set(simple)


def registered_block_items() -> set[str]:
    text = MOD_ITEMS.read_text(encoding="utf-8")
    pattern = re.compile(
        r'ITEMS\.registerItem\("([a-z0-9_./-]+)"\s*,\s*'
        r'props\s*->\s*new\s+BlockItem\(',
        re.MULTILINE,
    )
    return set(pattern.findall(text))


def registered_blocks() -> set[str]:
    text = MOD_BLOCKS.read_text(encoding="utf-8")
    return set(re.findall(
        r'BLOCKS\.registerBlock\(\s*"([a-z0-9_./-]+)"',
        text,
        re.MULTILINE,
    ))


def texture_path(ref: str) -> Path | None:
    if ref.startswith("#"):
        return None
    namespace, _, path = ref.partition(":")
    if not path:
        return None
    if namespace == "myvillage":
        return ASSET_ROOT / "textures" / f"{path}.png"
    return None


def model_path(ref: str) -> Path | None:
    namespace, _, path = ref.partition(":")
    if not path:
        return None
    if namespace == "myvillage":
        return ASSET_ROOT / "models" / f"{path}.json"
    return None


def validate_model(path: Path, errors: list[str], visited: set[Path] | None = None) -> None:
    visited = visited or set()
    if path in visited:
        return
    visited.add(path)
    if not path.exists():
        errors.append(f"missing_model:{path.relative_to(ROOT)}")
        return
    try:
        model = load_json(path)
    except ValueError as exc:
        errors.append(str(exc))
        return
    validate_model_data(model, path, errors, visited)


def validate_model_data(model: Any, path: Path, errors: list[str], visited: set[Path]) -> None:
    if not isinstance(model, dict):
        errors.append(f"invalid_model:{path.relative_to(ROOT)}")
        return
    if model.get("loader") == SEPARATE_TRANSFORMS_LOADER:
        # neoforge:separate_transforms: inline "base" model plus one inline model per display context.
        base = model.get("base")
        perspectives = model.get("perspectives")
        if not isinstance(base, dict) or not isinstance(perspectives, dict):
            errors.append(f"invalid_separate_transforms:{path.relative_to(ROOT)}")
        else:
            validate_model_data(base, path, errors, visited)
            for context, sub_model in perspectives.items():
                if context not in DISPLAY_CONTEXTS:
                    errors.append(f"invalid_separate_transforms_context:{path.relative_to(ROOT)}:{context}")
                validate_model_data(sub_model, path, errors, visited)

    parent = model.get("parent")
    if isinstance(parent, str):
        parent_path = model_path(parent)
        if parent_path is not None:
            validate_model(parent_path, errors, visited)

    textures = model.get("textures", {})
    if isinstance(textures, dict):
        for key, ref in textures.items():
            if not isinstance(ref, str):
                errors.append(f"invalid_texture_ref:{path.relative_to(ROOT)}:{key}")
                continue
            tex = texture_path(ref)
            if tex is None:
                continue
            if not tex.exists():
                errors.append(f"missing_texture:{tex.relative_to(ROOT)}")
                continue
            try:
                width, height = png_size(tex)
            except ValueError as exc:
                errors.append(str(exc))
                continue
            if width <= 0 or height <= 0:
                errors.append(f"invalid_texture_size:{tex.relative_to(ROOT)}:{width}x{height}")


def _generated_chain(model: dict[str, Any], depth: int = 0) -> bool:
    """True when the parent chain ends in builtin/generated (elements would be ignored)."""
    parent = model.get("parent")
    if not isinstance(parent, str) or depth > 8:
        return False
    if parent in GENERATED_PARENTS or parent == "builtin/generated":
        return True
    path = model_path(parent)
    if path is None or not path.is_file():
        return False
    try:
        return _generated_chain(load_json(path), depth + 1)
    except ValueError:
        return False


def validate_element_model(model: Any, error_key: str, errors: list[str]) -> None:
    """Contract of a 3D element item model (vanilla BlockElement limits)."""
    if not isinstance(model, dict):
        errors.append(f"{error_key}_model_3d_contract:not_an_object")
        return
    if _generated_chain(model):
        errors.append(f"{error_key}_model_3d_contract:generated_parent_ignores_elements")
    elements = model.get("elements")
    if not isinstance(elements, list) or not elements:
        errors.append(f"{error_key}_model_3d_contract:no_elements")
        return
    textures = model.get("textures", {}) if isinstance(model.get("textures"), dict) else {}
    for index, element in enumerate(elements):
        label = f"{error_key}_model_3d_contract:element_{index}"
        if not isinstance(element, dict):
            errors.append(f"{label}:not_an_object")
            continue
        corners = element.get("from"), element.get("to")
        if not all(isinstance(c, list) and len(c) == 3 and all(isinstance(v, (int, float)) for v in c)
                   for c in corners):
            errors.append(f"{label}:bounds")
            continue
        if any(v < -16 or v > 32 for c in corners for v in c):
            errors.append(f"{label}:outside_-16_32")
        rotation = element.get("rotation")
        if rotation is not None:
            if (not isinstance(rotation, dict) or rotation.get("axis") not in ("x", "y", "z")
                    or rotation.get("angle") not in (-45, -22.5, 0, 22.5, 45)):
                errors.append(f"{label}:rotation")
        faces = element.get("faces")
        if not isinstance(faces, dict) or not faces:
            errors.append(f"{label}:no_faces")
            continue
        for face, data in faces.items():
            if face not in ("north", "south", "east", "west", "up", "down") or not isinstance(data, dict):
                errors.append(f"{label}:face_{face}")
                continue
            texture = data.get("texture")
            if not isinstance(texture, str) or not texture.startswith("#") or texture[1:] not in textures:
                errors.append(f"{label}:face_{face}_texture")
            uv = data.get("uv")
            if uv is not None and (not isinstance(uv, list) or len(uv) != 4
                                   or any(not isinstance(v, (int, float)) or v < 0 or v > 16 for v in uv)):
                errors.append(f"{label}:face_{face}_uv")
    display = model.get("display")
    for context in ("thirdperson_righthand", "thirdperson_lefthand", "firstperson_righthand",
                    "firstperson_lefthand"):
        if not isinstance(display, dict) or not isinstance(display.get(context), dict):
            errors.append(f"{error_key}_model_3d_contract:display_{context}")


def validate_sword_model(item_id: str, model: Any, error_key: str, errors: list[str]) -> None:
    icon = f"myvillage:item/{item_id}"

    def is_icon(candidate: Any) -> bool:
        return (isinstance(candidate, dict) and candidate.get("parent") == "minecraft:item/handheld"
                and isinstance(candidate.get("textures"), dict)
                and candidate["textures"].get("layer0") == icon)

    model_3d_id = SWORD_3D_MODELS.get(item_id)
    if model_3d_id is None:
        if not is_icon(model):
            errors.append(f"{error_key}_model_contract")
        return
    # 3D sword: separate_transforms whose base is the element model and whose gui stays the 2D icon.
    perspectives = model.get("perspectives") if isinstance(model, dict) else None
    if (not isinstance(model, dict) or model.get("loader") != SEPARATE_TRANSFORMS_LOADER
            or model.get("base") != {"parent": model_3d_id}
            or not isinstance(perspectives, dict) or not is_icon(perspectives.get("gui"))):
        errors.append(f"{error_key}_model_contract")
        return
    if model.get("gui_light") != "front":
        errors.append(f"{error_key}_model_contract:gui_light")
    path = model_path(model_3d_id)
    if path is None or not path.is_file():
        errors.append(f"{error_key}_model_3d_missing")
        return
    try:
        model_3d = load_json(path)
    except ValueError:
        errors.append(f"{error_key}_model_3d_json")
        return
    validate_element_model(model_3d, error_key, errors)
    if isinstance(model_3d, dict) and isinstance(model_3d.get("display"), dict) and "gui" in model_3d["display"]:
        errors.append(f"{error_key}_model_3d_contract:gui_must_use_2d_icon")
    textures = model_3d.get("textures", {}) if isinstance(model_3d, dict) else {}
    for key, ref in (textures.items() if isinstance(textures, dict) else ()):
        if key == "particle":
            continue
        if not isinstance(ref, str) or not ref.startswith(f"myvillage:item/{item_id}_"):
            errors.append(f"{error_key}_model_3d_contract:texture_{key}")


def combat_weapon_items() -> set[str]:
    """Item ids (myvillage namespace, path only) that have a combat weapon entry."""
    found: set[str] = set()
    if not COMBAT_WEAPON_DATA.is_dir():
        return found
    for path in sorted(COMBAT_WEAPON_DATA.glob("*.json")):
        try:
            item = load_json(path).get("item")
        except (ValueError, AttributeError):
            continue
        if isinstance(item, str) and item.startswith("myvillage:"):
            found.add(item.split(":", 1)[1])
    return found


def registration_body(items_text: str, item_id: str) -> str | None:
    match = re.search(rf'ITEMS\.registerItem\(\s*"{re.escape(item_id)}"(?P<body>.*?\)\s*;)', items_text, re.DOTALL)
    return match.group("body") if match else None


def validate_combat_weapon_items(items_text: str, combat_items: set[str], errors: list[str]) -> None:
    """Every combat weapon is a CombatWeaponItem, and that class keeps its re-equip rule."""
    for item_id in sorted(combat_items):
        body = registration_body(items_text, item_id)
        if body is None or re.search(rf"new\s+{COMBAT_WEAPON_CLASS}\(", body) is None:
            errors.append(f"combat_weapon_not_{COMBAT_WEAPON_CLASS}:{item_id}")
    if not combat_items:
        return
    if not COMBAT_WEAPON_ITEM.is_file():
        errors.append(f"combat_weapon_item_missing:{COMBAT_WEAPON_ITEM.name}")
        return
    source = COMBAT_WEAPON_ITEM.read_text(encoding="utf-8")
    if (not re.search(rf"class\s+{COMBAT_WEAPON_CLASS}\s+extends\s+SwordItem\b", source)
            or any(needle not in source for needle in COMBAT_WEAPON_RULE)
            or any(needle in source for needle in COMBAT_WEAPON_RULE_FORBIDDEN)):
        errors.append("combat_weapon_item_contract:reequip_rule")


def validate_sword_registration(
        items_text: str,
        item_id: str,
        holder: str,
        error_key: str,
        attributes: tuple[int, str],
        errors: list[str],
        item_class: str = "SwordItem") -> None:
    declaration = re.search(
        rf"public\s+static\s+final\s+DeferredItem<SwordItem>\s+{re.escape(holder)}\s*=\s*"
        rf"(?P<body>.*?\)\s*;)",
        items_text,
        re.DOTALL,
    )
    if declaration is None:
        errors.append(f"{error_key}_registration_drift:DeferredItem<SwordItem> {holder}")
        return

    body = declaration.group("body")
    if re.search(rf'ITEMS\.registerItem\(\s*"{re.escape(item_id)}"', body) is None:
        errors.append(f'{error_key}_registration_drift:ITEMS.registerItem("{item_id}"')

    if re.search(rf"new\s+{item_class}\(", body) is None:
        errors.append(f"{error_key}_registration_drift:new {item_class}")

    bonus, speed = attributes
    exact_attributes = re.compile(
        rf"new\s+{item_class}\(\s*Tiers\.DIAMOND\s*,\s*"
        r"[A-Za-z_][A-Za-z0-9_]*\.attributes\(\s*"
        rf"SwordItem\.createAttributes\(\s*Tiers\.DIAMOND\s*,\s*{bonus}\s*,\s*{re.escape(speed)}\s*\)"
        r"\s*\)\s*\)",
        re.DOTALL,
    )
    if exact_attributes.search(body) is None:
        errors.append(
            f"{error_key}_registration_drift:SwordItem.createAttributes(Tiers.DIAMOND, {bonus}, {speed})")


def validate_swords(items_text: str, lang: dict[str, Any], zh_lang: dict[str, Any], errors: list[str]) -> None:
    combat_items = combat_weapon_items()
    validate_combat_weapon_items(items_text, combat_items, errors)
    for item_id, holder, en_name, zh_name, error_key, binary_alpha, attributes in SWORD_CONTRACTS:
        item_class = COMBAT_WEAPON_CLASS if item_id in combat_items else "SwordItem"
        validate_sword_registration(items_text, item_id, holder, error_key, attributes, errors, item_class)

        lang_key = f"item.myvillage.{item_id}"
        if lang.get(lang_key) != en_name:
            errors.append(f"{error_key}_en_us_name")
        if zh_lang.get(lang_key) != zh_name:
            errors.append(f"{error_key}_zh_cn_name")

        model_path = ASSET_ROOT / "models" / "item" / f"{item_id}.json"
        if not model_path.is_file():
            errors.append(f"{error_key}_model_missing")
        else:
            try:
                model = load_json(model_path)
            except ValueError:
                errors.append(f"{error_key}_model_json")
            else:
                validate_sword_model(item_id, model, error_key, errors)

        texture = ASSET_ROOT / "textures" / "item" / f"{item_id}.png"
        if not texture.is_file():
            errors.append(f"{error_key}_texture_missing")
        else:
            try:
                dimensions = png_size(texture)
            except ValueError:
                errors.append(f"{error_key}_texture_png")
            else:
                if dimensions != (64, 64):
                    errors.append(f"{error_key}_texture_dimensions:expected_64x64")
                if not png_has_alpha(texture):
                    errors.append(f"{error_key}_texture_alpha")
                elif binary_alpha:
                    try:
                        non_binary_alpha = png_non_binary_alpha_count(texture)
                    except (ValueError, struct.error, zlib.error):
                        errors.append(f"{error_key}_texture_alpha_decode")
                    else:
                        if non_binary_alpha:
                            errors.append(
                                f"{error_key}_texture_non_binary_alpha:{non_binary_alpha}")

    creative_positions = [
        items_text.find(f"output.accept({holder}.get())")
        for holder in CREATIVE_SWORD_ORDER
    ]
    if any(position < 0 for position in creative_positions) or creative_positions != sorted(creative_positions):
        errors.append(
            "sword_creative_order:rideable->qingfeng->xuanyue->chilian->qingxiao->lingxiao->spirit_stone")

    tag_path = ROOT / "src/main/resources/data/minecraft/tags/item/swords.json"
    if not tag_path.is_file():
        errors.append("qingfeng_sword_tag_missing")
    else:
        try:
            tag = load_json(tag_path)
        except ValueError as exc:
            errors.append(str(exc))
        else:
            values = tag.get("values", [])
            if tag.get("replace") is not False or not isinstance(values, list):
                errors.append("qingfeng_sword_tag_contract")
                values = []
            for item_id, _, _, _, error_key, _, _ in SWORD_CONTRACTS:
                if f"myvillage:{item_id}" not in values:
                    errors.append(f"{error_key}_sword_tag_contract")


def validate_qingfeng_recipe(errors: list[str]) -> None:
    recipe_path = ROOT / "src/main/resources/data/myvillage/recipe/qingfeng_sword.json"
    if not recipe_path.is_file():
        errors.append("qingfeng_recipe_missing")
        return

    try:
        recipe = load_json(recipe_path)
    except ValueError as exc:
        errors.append(str(exc))
        return
    expected_pattern = ["D", "D", "S"]
    if (recipe.get("type") != "minecraft:crafting_shaped"
            or recipe.get("pattern") != expected_pattern
            or recipe.get("key", {}).get("D", {}).get("item") != "minecraft:diamond"
            or recipe.get("key", {}).get("S", {}).get("item") != "minecraft:stick"
            or recipe.get("result", {}).get("id") != "myvillage:qingfeng_sword"):
        errors.append("qingfeng_recipe_contract")


def validate() -> list[str]:
    errors: list[str] = []
    items = registered_items()
    block_items = registered_block_items()
    blocks = registered_blocks()
    lang = load_json(LANG)
    zh_lang = load_json(ZH_LANG)
    items_text = MOD_ITEMS.read_text(encoding="utf-8")
    rockery_text = ROCKERY_BLOCK.read_text(encoding="utf-8") if ROCKERY_BLOCK.exists() else ""

    if not items:
        errors.append("no_registered_items")

    for item_id in sorted(items):
        item_model = ASSET_ROOT / "models" / "item" / f"{item_id}.json"
        if not item_model.exists():
            errors.append(f"missing_item_model:{item_model.relative_to(ROOT)}")
        else:
            validate_model(item_model, errors)

        item_key = f"item.myvillage.{item_id}"
        block_key = f"block.myvillage.{item_id}"
        if item_key not in lang and block_key not in lang:
            errors.append(f"missing_lang:{item_key}|{block_key}")

    for item_id in sorted(block_items):
        if item_id not in blocks:
            errors.append(f"missing_block_registration:{item_id}")
        blockstate = ASSET_ROOT / "blockstates" / f"{item_id}.json"
        if not blockstate.exists():
            errors.append(f"missing_blockstate:{blockstate.relative_to(ROOT)}")
        else:
            try:
                blockstate_data = load_json(blockstate)
            except ValueError as exc:
                errors.append(str(exc))
            else:
                variants = blockstate_data.get("variants", {})
                if not isinstance(variants, dict) or not variants:
                    errors.append(f"missing_blockstate_variants:{blockstate.relative_to(ROOT)}")

    if "rockery_block" in block_items:
        if "getCloneItemStack(" not in rockery_text or "ROCKERY_BLOCK_ITEM.get()" not in rockery_text:
            errors.append("missing_pick_block_clone:myvillage:rockery_block")

    validate_swords(items_text, lang, zh_lang, errors)
    validate_qingfeng_recipe(errors)

    return errors


def main() -> int:
    errors = validate()
    if errors:
        for error in errors:
            print(error)
        return 1
    print("mod item validation passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
